### PR TITLE
Issue 15: Add ForkMe Ribbon

### PR DESCRIPTION
**Pull request by jackswiney**
Added GitHub Pages for this project. Currently it's pointing to this branch. It can be found [here](https://boeing.github.io/config-file-validator/). 

This MR adds the GitHub "Fork Me" Ribbon to our Readme, so it will also be displayed on GitHub Pages.

### CODE REVIEW

**Comment by jd4235** [comment]
I see you defined a new workflow [here](https://github.com/Boeing/config-file-validator/actions/workflows/pages/pages-build-deployment).  Where I can view the definition of that workflow?  For example, Clay's Go pipeline is in .github/workflows.

**Comment by jd4235** [comment]
LGTM

**Comment by jackswiney** [comment]
> I see you defined a new workflow [here](https://github.com/Boeing/config-file-validator/actions/workflows/pages/pages-build-deployment). Where I can view the definition of that workflow (i.e. the steps and their definitions equivalent to Gitlab yml)? For example, Clay's Go pipeline is in .github/workflows.

It's built in, now that github pages is enabled for the project. I didn't define anything, just updated project settings.

**Review by jd4235 — APPROVED** [review]

**Comment by kehoecj** [comment]
My only concern is now the README looks off when navigating to the the [project page](https://github.com/Boeing/config-file-validator/tree/jswiney_issue15#readme) because of the ribbon being right under the logo. Is there any way to hide it on the markdown rendering but display it on the HTML?

**Comment by jackswiney** [comment]
> My only concern is now the README looks off when navigating to the the [project page](https://github.com/Boeing/config-file-validator/tree/jswiney_issue15#readme) because of the ribbon being right under the logo. Is there any way to hide it on the markdown rendering but display it on the HTML?

Opened a new PR https://github.com/Boeing/config-file-validator/pull/31 with changes to use `index.md` instead of readme

**Pull request closed without merging**
