### PR TITLE
feat(finder): Add support for multiple search paths

### LINKED ISSUE #45: Add support for multiple search paths
## Description

The config-file-validator currently only supports a single search path. Users will probably want the ability to specify several search paths with a single execution and have the results rolled up into a single report.

```
validator /path/to/search/a /path/to/search/b
```

### PR DESCRIPTION
**Pull request by gokulav137**
Resolves #45

### CODE REVIEW

**Review by jackswiney — APPROVED** [review]
LGTM

**Review by kehoecj — CHANGES_REQUESTED** [review]
If I pass in multiple instances of the same path `/validator /test/fixtures/subdir /test/fixtures/subdir` the validator will scan the same path twice. I can't think of a valid reason a user would want to double scan so it's most likely going to be accidental. I think we should either do a check and raise an error if there are duplicate paths or update the duplicate finder to only scan a path once

**Comment by gokulav137** [comment]
I changed my approach to solve this issue. Instead adding a composite pattern, I switched to removing duplicates from the files found during the walk.

This change was done as the composite method will make having a depth filter more complex.

Currently files with absolute path that is already seen will be ignored by the finder and won't be passed down further for processing.
> Yes, that'd be another issue. So two things to address:
>
> If the same path is specified in on he command line only one will be scanned and reported (i.e. no duplicate results)
> If multiple paths are specified that both contain the a directory as part of the recursive scanning only one will be reported

Hope this fixes these concerns @kehoecj

**Comment by kehoecj** [comment]
@gokulav137 There was a recent MR that added the ability to specify depth when scanning directories. Can you merge in the lastest change from master and refactor your current implementation to make sure it supports depth. Thanks!

**Comment by gokulav137** [comment]
Sure @kehoecj, merged the changes to the branch. 

Did a sanity locally, these changes work with depth.

```
go run cmd/validator/validator.go --depth=1 . .
    ✓ .github/workflows/go.yml
    ✓ .github/workflows/release.yml
    ✓ test/fixtures/good.hcl
    ✓ test/fixtures/good.ini
    ✓ test/fixtures/good.json
    ✓ test/fixtures/good.properties
    ✓ test/fixtures/good.toml
    ✓ test/fixtures/good.yaml
Summary: 8 succeeded, 0 failed
```

**Comment by gokulav137** [comment]
I found a few more issues and consolidated them. Shall I raise a bug on this @kehoecj 

The depth skip check is based on the path rather than the relative depth from the rootPath to the path.
```
$ go run cmd/validator/validator.go --depth=1 ./test/fixtures/subdir/
Summary: 0 succeeded, 0 failed
$ go run cmd/validator/validator.go --depth=2 ./test/fixtures/subdir/
Summary: 0 succeeded, 0 failed
$ go run cmd/validator/validator.go --depth=3 ./test/fixtures/subdir/
Summary: 0 succeeded, 0 failed
$ go run cmd/validator/validator.go --depth=4 ./test/fixtures/subdir/
    × test/fixtures/subdir/bad.json
        error: Error at line 3 column 14: invalid character ':' after array element
    × test/fixtures/subdir/bad.toml
        error: Error at line 6 column 6: toml: expected character =
    × test/fixtures/subdir/bad.yml
        error: yaml: line 3: did not find expected '-' indicator
    ✓ test/fixtures/subdir/good.json
Summary: 1 succeeded, 3 failed
```

The depth check is based on counting separators in the path that can cause inconsistency if not checked from a clean path.
```
$ go run cmd/validator/validator.go --depth=3 test/fixtures/subdir/
    × test/fixtures/subdir/bad.json
        error: Error at line 3 column 14: invalid character ':' after array element
    × test/fixtures/subdir/bad.toml
        error: Error at line 6 column 6: toml: expected character =
    × test/fixtures/subdir/bad.yml
        error: yaml: line 3: did not find expected '-' indicator
    ✓ test/fixtures/subdir/good.json
Summary: 1 succeeded, 3 failed
exit status 1
$ go run cmd/validator/validator.go --depth=3 ./test/fixtures/subdir/
Summary: 0 succeeded, 0 failed
```

The depth param set to 1 still parses files 2 directories down
```
$ go run cmd/validator/validator.go --depth=1 .
    ✓ .github/workflows/go.yml
    ✓ .github/workflows/release.yml
    ✓ test/fixtures/good.hcl
    ✓ test/fixtures/good.ini
    ✓ test/fixtures/good.json
    ✓ test/fixtures/good.properties
    ✓ test/fixtures/good.toml
    ✓ test/fixtures/good.yaml
```

This is the code in question:
https://github.com/Boeing/config-file-validator/blob/main/pkg/finder/fsfinder.go#L91
```go
err := filepath.WalkDir(fsf.PathRoot,
func(path string, dirEntry fs.DirEntry, err error) error {
	// determine if directory is in the excludeDirs list
	if dirEntry.IsDir() && fsf.Depth != nil && strings.Count(path, string(os.PathSeparator)) > *fsf.Depth {
		// Skip processing the directory
		return fs.SkipDir // This is not reported as an error by filepath.WalkDir
	}
```

**Comment by kehoecj** [comment]
> I found a few more issues and consolidated them. Shall I raise a bug on this @kehoecj
> 
> The depth skip check is based on the path rather than the relative depth from the rootPath to the path.
> 
> ```
> $ go run cmd/validator/validator.go --depth=1 ./test/fixtures/subdir/
> Summary: 0 succeeded, 0 failed
> $ go run cmd/validator/validator.go --depth=2 ./test/fixtures/subdir/
> Summary: 0 succeeded, 0 failed
> $ go run cmd/validator/validator.go --depth=3 ./test/fixtures/subdir/
> Summary: 0 succeeded, 0 failed
> $ go run cmd/validator/validator.go --depth=4 ./test/fixtures/subdir/
>     × test/fixtures/subdir/bad.json
>         error: Error at line 3 column 14: invalid character ':' after array element
>     × test/fixtures/subdir/bad.toml
>         error: Error at line 6 column 6: toml: expected character =
>     × test/fixtures/subdir/bad.yml
>         error: yaml: line 3: did not find expected '-' indicator
>     ✓ test/fixtures/subdir/good.json
> Summary: 1 succeeded, 3 failed
> ```
> 
> The depth check is based on counting separators in the path that can cause inconsistency if not checked from a clean path.
> 
> ```
> $ go run cmd/validator/validator.go --depth=3 test/fixtures/subdir/
>     × test/fixtures/subdir/bad.json
>         error: Error at line 3 column 14: invalid character ':' after array element
>     × test/fixtures/subdir/bad.toml
>         error: Error at line 6 column 6: toml: expected character =
>     × test/fixtures/subdir/bad.yml
>         error: yaml: line 3: did not find expected '-' indicator
>     ✓ test/fixtures/subdir/good.json
> Summary: 1 succeeded, 3 failed
> exit status 1
> $ go run cmd/validator/validator.go --depth=3 ./test/fixtures/subdir/
> Summary: 0 succeeded, 0 failed
> ```
> 
> The depth param set to 1 still parses files 2 directories down
> 
> ```
> $ go run cmd/validator/validator.go --depth=1 .
>     ✓ .github/workflows/go.yml
>     ✓ .github/workflows/release.yml
>     ✓ test/fixtures/good.hcl
>     ✓ test/fixtures/good.ini
>     ✓ test/fixtures/good.json
>     ✓ test/fixtures/good.properties
>     ✓ test/fixtures/good.toml
>     ✓ test/fixtures/good.yaml
> ```
> 
> This is the code in question: https://github.com/Boeing/config-file-validator/blob/main/pkg/finder/fsfinder.go#L91
> 
> ```go
> err := filepath.WalkDir(fsf.PathRoot,
> func(path string, dirEntry fs.DirEntry, err error) error {
> 	// determine if directory is in the excludeDirs list
> 	if dirEntry.IsDir() && fsf.Depth != nil && strings.Count(path, string(os.PathSeparator)) > *fsf.Depth {
> 		// Skip processing the directory
> 		return fs.SkipDir // This is not reported as an error by filepath.WalkDir
> 	}
> ```

Yes please raise a bug

**Review by kehoecj — APPROVED** [review]
LGTM - validated with local testing

**Review by jd4235 — APPROVED** [review]

**Pull request merged**
