### PR TITLE
code review

### PR DESCRIPTION
**Pull request by ccoVeille**
I started looking at your code as I'm using it.

Some are existing errors, some are things that could become errors later with a refactoring

Here is a PR about fixing them.

- **chore: format files before working on them**
- **fix: make sure to always wrap errors**
- **fix: uncaught error in json reporter**
- **fix: errors have to be manipulated with care**
- **chore: fix some typos and error in the struct**
- **chore: remove unused receivers**

### CODE REVIEW

**Comment by ccoVeille** [comment]
There is one more error in the code I would like to fix, but it would require to refactor the code a bit, so I will wait to see if you are accepting this PR first :smile:

**Comment by ccoVeille** [comment]
You are not fun :smile: you also started fixing in #131 issue I have fixed there :stuck_out_tongue_closed_eyes: 

I will wait for your PR to be merged then I will fix the conflicts

**Comment by ccoVeille** [comment]
You are not fun @HakanVardarr 😄 you also started fixing in https://github.com/Boeing/config-file-validator/pull/131 issue I have fixed there 😝

I will wait for your PR to be merged then I will fix the conflicts

**Comment by HakanVardarr** [comment]
Sorry for that. :(

**Comment by kehoecj** [comment]
Much appreciated @ccoVeille ❤️ Excited to take a look through the PR.

**Comment by ccoVeille** [comment]
For record, you can review but I will wait for the #131 to be merged. I'm confident in being able to fix the conflicts easily.

**Comment by ccoVeille** [comment]
Here we go !

**Review by kehoecj — APPROVED** [review]
LGTM - thanks for the code review. I learned some new things 😄 Do you want me to merge this now or wait for the linter?

**Comment by ccoVeille** [comment]
@kehoecj please merge

I will rebase and push back the linter

**Comment by ccoVeille** [comment]
Also fixed #134

**Pull request merged**
