### PR TITLE
Add support upper and mixed case file extensions #99

### PR DESCRIPTION
**Pull request by iyoshiha**
I use `string.EqualFold` instead of `==`.  I added tests and test file for upper and mixed case extension files.
issues: https://github.com/Boeing/config-file-validator/issues/99

### CODE REVIEW

**Review by jackswiney — APPROVED** [review]
LGTM

**Review by kehoecj — APPROVED** [review]
LGTM! Thanks for the contribution

**Review by jd4235 — APPROVED** [review]
LGTM

**Comment by kehoecj** [comment]
Thank you for the PR @iyoshiha !

**Pull request merged**
